CREATE TABLE batches
(
    id         INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    root_hash  BINARY(32) NOT NULL,
    spent_coin BINARY(32) NOT NULL,
    block_hash BINARY(32),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);