CREATE TABLE records
(
    id         INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    hash       BINARY(32) NOT NULL,
    batch_id   INTEGER UNSIGNED,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);